#@BASE=http://localhost:4200/api

### Users ###
GET {{BASE}}/hello

###
GET {{BASE}}/posts
Content-Type: application/json

###

### get access token

POST https://auth.htl-leonding.ac.at/realms/htlleonding/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = htlleonding-service &
client_secret = rmDAPoC71cELHwgPan5ybDnMNFY3VjsX &
grant_type = password &
username = {{username}} &
password = {{password}} &
  #username = student &
  #password = passme &
scope = openid

> {%
    client.global.set("auth_token", response.body.access_token);
    client.log("Bearer: " + client.global.get("auth_token"));
%}

###

GET https://auth.htl-leonding.ac.at/realms/htlleonding/protocol/openid-connect/userinfo
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###